export const PhaserEvents = {
  PLAYER_STATS_UPDATED: 'player:statsUpdated',
  PLAYER_HP_CHANGED: 'player:hpChanged',
  PLAYER_XP_CHANGED: 'player:xpChanged',
  INVENTORY_UPDATED: 'inventory:updated',
  EQUIPMENT_CHANGED: 'equipment:changed',
  COMBAT_HIT: 'combat:hit',
  COMBAT_DEATH: 'combat:death',
  LOOT_DROPPED: 'loot:dropped',
  QUEST_STARTED: 'quest:started',
  QUEST_PROGRESS: 'quest:progress',
  QUEST_COMPLETED: 'quest:completed',
  SHOP_OPENED: 'shop:opened',
  SHOP_ITEM_BOUGHT: 'shop:itemBought',
  DIALOG_START: 'dialog:start',
  DIALOG_OPTION: 'dialog:option',
  SKILL_READY: 'skill:ready',
  NPC_STATE_CHANGED: 'npc:stateChanged',
  SCENE_LOADED: 'scene:loaded',
  INTERACTION: 'interaction',
  ENEMY_SPAWNED: 'enemy:spawned',
  ENEMY_KILLED: 'enemy:killed',
} as const;

export const ReactCommands = {
  USE_ITEM: 'react:useItem',
  EQUIP_ITEM: 'react:equipItem',
  UNEQUIP_ITEM: 'react:unequipItem',
  CAST_SKILL: 'react:castSkill',
  INTERACT: 'react:interact',
  QUEST_ACCEPT: 'react:questAccept',
  QUEST_DECLINE: 'react:questDecline',
  SHOP_BUY: 'react:shopBuy',
  SHOP_CLOSE: 'react:shopClose',
  DIALOG_OPTION: 'react:dialogOption',
  DIALOG_CLOSE: 'react:dialogClose',
} as const;