mindmap
  root((Kleeblatt Adventure<br/>Prototyp-Ergänzungen))
    Gebäude & Strukturen
      Schmiede (Upgrade/Reparatur)
      Gasthaus (HP/Mana/Save)
      Laden (Consumables)
      Schrein (Respawn-Markierung)
      Dungeon-Portal (Zonen-Wechsel)
    Erweiterte Ausrüstung
      Neue Slots
        Helm (Def/Sicht)
        Stiefel (Speed)
        Schild (Melee Block)
      Accessoires
        Ringe (Crit/Luck)
        Amulette (Drop-Rate)
      Verbrauchsgüter
        Heiltrank (HP)
        Manatrank (Mana)
    Klassen-Skills
      Melee
        Zähigkeit (Passiv HP)
        Schildstoß (Aktiv CC)
      Ranged
        Leichtfüßigkeit (Passiv Speed)
        Mehrfachschuss (Aktiv AoE)
      Mage
        Meditation (Passiv Mana Reg)
        Frostnova (Aktiv Slow)
    Adventure-Mechaniken
      Quest-Indikatoren (!)
      Zerstörbare Objekte (Loot)
      Loot-Animation (Glow)
      Mini-Map (Orientierung)
    Blockchain-Visuals
      Raritäts-Glow (Farbrahmen)
      Secured-Badge (Schloss-Icon)
