export const UI_ASSETS = {
  bars: {
    red: Array.from({ length: 7 }, (_, i) => `/assets/ui/redbar_${String(i).padStart(2, "0")}.png`),
    blue: Array.from({ length: 6 }, (_, i) => `/assets/ui/bluebar_${String(i).padStart(2, "0")}.png`),
    green: Array.from({ length: 7 }, (_, i) => `/assets/ui/greenbar_${String(i).padStart(2, "0")}.png`),
  },
  icons: {
    sword: "/assets/ui/sword.png",
    axe: "/assets/ui/axe.png",
    hammer: "/assets/ui/hammer.png",
    pickaxe: "/assets/ui/pickaxe.png",
    rod: "/assets/ui/rod.png",
    water: "/assets/ui/water.png",
    basket: "/assets/ui/basket.png",
    shovel: "/assets/ui/shovel.png",
    stopwatch: "/assets/ui/stopwatch.png",
    sandtimer: "/assets/ui/sandtimer.png",
    plant: "/assets/ui/plant.png",
    search: "/assets/ui/search.png",
    playercount: "/assets/ui/playercount.png",
    indicator: "/assets/ui/indicator.png",
    confirm: "/assets/ui/confirm.png",
    cancel: "/assets/ui/cancel.png",
  },
  expressions: {
    alerted: "/assets/ui/expression_alerted.png",
    attack: "/assets/ui/expression_attack.png",
    chat: "/assets/ui/expression_chat.png",
    confused: "/assets/ui/expression_confused.png",
    love: "/assets/ui/expression_love.png",
    stress: "/assets/ui/expression_stress.png",
    working: "/assets/ui/expression_working.png",
  },
  cursors: {
    cursor1: "/assets/ui/cursor_01.png",
    cursor2: "/assets/ui/cursor_02.png",
    cursor3: "/assets/ui/cursor_03.png",
    cursor4: "/assets/ui/cursor_04.png",
    cursor5: "/assets/ui/cursor_05.png",
  },
  labels: {
    left: "/assets/ui/label_left.png",
    middle: "/assets/ui/label_middle.png",
    right: "/assets/ui/label_right.png",
  },
  selection: {
    bl: "/assets/ui/selectbox_bl.png",
    br: "/assets/ui/selectbox_br.png",
    tl: "/assets/ui/selectbox_tl.png",
    tr: "/assets/ui/selectbox_tr.png",
    dots: "/assets/ui/select_dots.png",
    dotsLarge: "/assets/ui/select_dots_large.png",
  },
  hands: {
    open1: "/assets/ui/hand_open_01.png",
    open2: "/assets/ui/hand_open_02.png",
    closed1: "/assets/ui/hand_closed_01.png",
    closed2: "/assets/ui/hand_closed_02.png",
  },
  happiness: Array.from({ length: 4 }, (_, i) => `/assets/ui/happiness_0${i + 1}.png`),
  itemdisc: ["/assets/ui/itemdisc_01.png", "/assets/ui/itemdisc_02.png"],
  arrows: {
    up: "/assets/ui/arrow_up.png",
    upAlt: "/assets/ui/arrow_up-1.png",
    right: "/assets/ui/arrow_right.png",
    left: "/assets/ui/arrow_left.png",
  },
} as const;

export type UiAssetPaths = typeof UI_ASSETS;
